version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.inject:guice
    versions:
    - 5.0.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
